services:
  - type: web
    name: echosphere
    runtime: python
    buildCommand: ""
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    plan: free
    region: singapore
